---
- name: Deploy Apache Docker Container
  hosts: all
  become: yes

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Install pip
      apt:
        name: python3-pip
        state: present

    - name: Install Docker Python module
      pip:
        name: docker
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Create a Docker network
      docker_network:
        name: apache_network
        ipam_config:
          - subnet: 172.168.10.0/30

    - name: Deploy Apache container
      docker_container:
        name: apache_container
        image: httpd:latest
        state: started
        restart_policy: always
        networks:
          - name: apache_network
        ports:
          - "80:80"
        volumes:
          - "{{ playbook_dir }}/html:/usr/local/apache2/htdocs/"
        networks_cli_compatible: yes
        container_default_behavior: compatibility

